# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-06 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoVideoFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ogg_480_file', models.FileField(upload_to='Videos/TranscodingVideo/P480', verbose_name='480图片路径')),
                ('wav_360_file', models.FileField(upload_to='Videos/TranscodingVideo/P360', verbose_name='360图片路径')),
                ('mkv_720_file', models.FileField(upload_to='Videos/TranscodingVideo/P720', verbose_name='720图片路径')),
            ],
            options={
                'verbose_name_plural': '转码后的视频',
            },
        ),
        migrations.CreateModel(
            name='CategoryImg',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=32, verbose_name='分类标题')),
            ],
            options={
                'verbose_name_plural': '图片分类',
            },
        ),
        migrations.CreateModel(
            name='CategoryVid',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=32, verbose_name='分类标题')),
            ],
            options={
                'verbose_name_plural': '视频分类',
            },
        ),
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.ImageField(default='media/images', max_length=32, upload_to='images/', verbose_name='图片路径')),
                ('title', models.CharField(max_length=16, verbose_name='标题')),
                ('summary', models.CharField(max_length=128, verbose_name='简介')),
                ('flag', models.IntegerField(choices=[(1, '正常'), (0, '删除')], verbose_name='标记图片状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '图片',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sex', models.CharField(choices=[('man', '男'), ('wman', '女')], default='男', max_length=32)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '用户',
            },
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.FileField(max_length=32, upload_to='Video/', verbose_name='视频路径')),
                ('title', models.CharField(max_length=16, verbose_name='标题')),
                ('summary', models.CharField(max_length=128, verbose_name='简介')),
                ('flag', models.IntegerField(choices=[(1, '正常'), (0, '删除')], verbose_name='标记图片状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '视频',
            },
        ),
        migrations.AddField(
            model_name='categoryvid',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viodes.User', verbose_name='所属用户'),
        ),
        migrations.AddField(
            model_name='categoryimg',
            name='Img',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viodes.User', verbose_name='所属用户'),
        ),
    ]
